# Generated by Django 4.1.5 on 2023-02-05 04:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
