# Generated by Django 4.1.5 on 2023-02-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(choices=[(20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (76, '76'), (77, '77'), (78, '78'), (79, '79'), (80, '80'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85'), (86, '86'), (87, '87'), (88, '88'), (89, '89'), (90, '90'), (91, '91'), (92, '92'), (93, '93'), (94, '94'), (95, '95'), (96, '96'), (97, '97'), (98, '98'), (99, '99'), (100, '100')], default=20)),
                ('sex', models.IntegerField(choices=[(0, 'Female'), (1, 'Male')], default=0)),
                ('cp', models.IntegerField(choices=[(0, 'Typical angina'), (1, 'Atypical angina'), (2, 'Non-anginal pain'), (3, 'Asymptomatic')], default=0)),
                ('trtbps', models.FloatField(default=0.0)),
                ('chol', models.FloatField(default=0.0)),
                ('fbs', models.IntegerField(choices=[(0, '<120mg/dl'), (1, '>120mg/dl')], default=0)),
                ('restecg', models.IntegerField(choices=[(0, 'Normal'), (1, 'ST-T wave abnormality'), (2, 'Left ventricular hypertrophy')], default=0)),
                ('thalach', models.FloatField(default=0.0)),
                ('exng', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('oldpeak', models.FloatField(default=0.0)),
                ('slp', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('caa', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('thall', models.IntegerField(choices=[(0, 'Normal'), (1, 'Fixed defect'), (2, 'Reversable defect')], default=0)),
            ],
        ),
    ]
