# Generated by Django 4.1.5 on 2023-02-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartattackclassification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hac',
            name='output',
            field=models.IntegerField(choices=[(0, '0 - No HA'), (1, '1 - HA')], default=0),
        ),
        migrations.AlterField(
            model_name='hac',
            name='age',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (76, '76'), (77, '77'), (78, '78'), (79, '79'), (80, '80'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85'), (86, '86'), (87, '87'), (88, '88'), (89, '89'), (90, '90'), (91, '91'), (92, '92'), (93, '93'), (94, '94'), (95, '95'), (96, '96'), (97, '97'), (98, '98'), (99, '99'), (100, '100'), (101, '101'), (102, '102'), (103, '103'), (104, '104'), (105, '105'), (106, '106'), (107, '107'), (108, '108'), (109, '109'), (110, '110'), (111, '111'), (112, '112'), (113, '113'), (114, '114'), (115, '115'), (116, '116'), (117, '117'), (118, '118'), (119, '119')], default=20),
        ),
        migrations.AlterField(
            model_name='hac',
            name='cp',
            field=models.IntegerField(choices=[(1, '1 - Typical angina'), (2, '2 - Atypical angina'), (3, '3 - Non-anginal pain'), (4, '4 - Asymptomatic')], default=0),
        ),
        migrations.AlterField(
            model_name='hac',
            name='exng',
            field=models.IntegerField(choices=[(0, '0 - No'), (1, '1 - Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='hac',
            name='fbs',
            field=models.IntegerField(choices=[(0, '0 - <120mg/dl'), (1, '1 - >120mg/dl')], default=0),
        ),
        migrations.AlterField(
            model_name='hac',
            name='restecg',
            field=models.IntegerField(choices=[(0, '0 - Normal'), (1, '1 - ST-T wave abnormality'), (2, '2 - Left ventricular hypertrophy')], default=0),
        ),
        migrations.AlterField(
            model_name='hac',
            name='sex',
            field=models.IntegerField(choices=[(0, '0 - Female'), (1, '1 - Male')], default=0),
        ),
        migrations.AlterField(
            model_name='hac',
            name='slp',
            field=models.IntegerField(choices=[(0, '0 - No'), (1, '1 - Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='hac',
            name='thall',
            field=models.IntegerField(choices=[(0, '0 - Normal'), (1, '1 - Fixed defect'), (2, '2 - Reversable defect')], default=0),
        ),
    ]
