# Generated by Django 4.1.5 on 2023-02-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heartattackclassification', '0002_hac_output_alter_hac_age_alter_hac_cp_alter_hac_exng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hac',
            old_name='thalach',
            new_name='thalachh',
        ),
    ]
