# Generated by Django 4.1.5 on 2023-02-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('how_found', models.PositiveSmallIntegerField(choices=[(1, 'LinkedIn'), (2, 'Resume'), (3, 'GitHub'), (4, 'Other')])),
                ('additional_info', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('agreed_to_terms', models.BooleanField()),
            ],
        ),
    ]
