# Generated by Django 4.1.5 on 2023-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contactform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='agreed_to_terms',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='how_found',
        ),
        migrations.RemoveField(
            model_name='contactform',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactform',
            name='find',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactform',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='contactform',
            name='terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='additional_info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
