# Generated by Django 4.1.5 on 2023-02-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_contactform_agreed_to_terms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('tech', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
