# Generated by Django 4.1.5 on 2023-02-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ml'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactform',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/'),
        ),
    ]
