# Generated by Django 4.1.7 on 2023-03-10 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_cert_alter_contactform_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
